import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Skills from "../components/Skills";
import { skills } from "../data";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Lusigi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="relative min-h-[90vh] flex flex-col justify-center mt-0 py-[30px] left-[8%]  ">
          <h1 className="uppercase font-light tracking-widest text-[14px] font-Poppins px-10 lg:px-2">
            Hi! My Name is Brian Lusigi
          </h1>

          <p className=" text-[3.2rem] lg:text-[5em] my-[30px] font-Magenda font-extrabold px-10 lg:px-2 lg:max-w-[700px]">
            I solve problems through design and technology
          </p>

          <p className="font-light font-Poppins tracking-widest text-[17px] max-w-[1600px] mr-auto leading-6 px-10 lg:px-2">
            From web design → front-end development I create work that sits at
            the intersection of art, design and technology.
          </p>
        </div>
        <div>
          {/* <svg
            className="fixed bottom-0 left-1/2"
            width="16"
            height="30"
            viewBox="0 0 16 66"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="M7.29289 65.7071C7.68342 66.0976 8.31658 66.0976 8.70711 65.7071L15.0711 59.3431C15.4616 58.9526 15.4616 58.3195 15.0711 57.9289C14.6805 57.5384 14.0474 57.5384 13.6569 57.9289L8 63.5858L2.34315 57.9289C1.95262 57.5384 1.31946 57.5384 0.928932 57.9289C0.538408 58.3195 0.538408 58.9526 0.928932 59.3431L7.29289 65.7071ZM7 0L7 65H9L9 0L7 0Z"
              fill="#000"
            />
          </svg> */}
        </div>
        <div className="relative h-[180px] md:mt-[30px] w-[1px] bg-black left-1/2 mb-[50px] lg:mb-[100px]" />
        <div className="flex flex-col justify-center items-center space-y-8 max-w-[600px] mx-auto left-[8%]">
          <h3 className=" text-3xl font-bold font-Magenda lg:text-6xl">
            Agility Meets creativity
          </h3>
          <p className=" font-Poppins text-left lg:text-center px-10  md:px-0 ">
            I thrive at the crossroads of creativity and practicality, which
            puts me in the perfect position to bring your vision to life
          </p>
          <Link href="/about">
            <a className="px-5 py-2 border border-gray-400 rounded-full ">
              Learn More
            </a>
          </Link>
        </div>
        <div className="relative h-[180px] mt-[50px] md:mt-[100px] w-[1px] bg-black left-1/2 mb-[50px] lg:mb-[100px]" />
        <div className="flex flex-col justify-center items-center ">
          <h3 className=" text-3xl font-bold font-Magenda mb-[40px] lg:text-6xl">
            Featured Work
          </h3>
          <div className="relative h-[0.4px] w-[350px] bg-gray-300 mb-[50px] ml-14 lg:ml-auto  lg:w-[900px] mx-auto " />
        </div>
        <section>
          <div>
            <div className="flex flex-col md:flex-row justify-around ">
              <div className="px-10 flex flex-col space-y-5 mb-[50px] md:border-r-[1px] md:border-gray-200 md:pr-[8%] ">
                <div className="flex flex-col space-y-4 mb-[20px] ">
                  <h4 className="text-2xl font-bold  font-Magenda">
                    Tabitha Alms
                  </h4>

                  <a
                    href="https://tabithaalms.org"
                    className="text-xs uppercase  font-Poppins underline underline-offset-1"
                  >
                    website
                  </a>
                </div>
                <div className="flex flex-col space-y-6 font-Poppins">
                  <p className="font-Poppins text-[15px] ">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Mollitia
                  </p>
                  <Link href="/">
                    <a className="text-sm underline pb-2">Read More</a>
                  </Link>
                </div>
                <div>
                  <div
                    className="card__tabitha relative w-[358px] md:w-[480px] h-[318px] md:h-[420px] 
                   "
                  >
                    <img
                      src="/Landing.png"
                      className="absolute bottom-10 md:bottom-20 w-[320px] md:w-[448px] h-[220px] md:h-[280px] left-5 md:left-4 object-cover"
                      alt=""
                    />
                  </div>
                </div>
              </div>
              <div className=" px-10 flex flex-col space-y-5 ">
                <div>
                  <div className="relative w-[358px] md:w-[480px] h-[318px] md:h-[420px] card__travel ">
                    <img
                      src="/Travel.png"
                      className="absolute bottom-10 md:bottom-14 w-[320px] md:w-[448px] h-[220px] md:h-[320px] left-5 md:left-4 object-contain"
                      alt=""
                    />
                  </div>
                </div>
                <div className="flex flex-col space-y-4 mb-[20px] ">
                  <h4 className="text-2xl font-bold  font-Magenda">
                    Travel Adventures
                  </h4>

                  <Link href="/">
                    <a className="text-xs uppercase  font-Poppins underline underline-offset-1">
                      website
                    </a>
                  </Link>
                </div>
                <div className="flex flex-col space-y-6 font-Poppins">
                  <p className="font-Poppins text-[15px] ">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Mollitia
                  </p>
                  <Link href="/">
                    <a className="text-sm underline pb-2">Read More</a>
                  </Link>
                </div>
              </div>
            </div>
          </div>
          <div className="border-t-[1px] border-gray-200  max-w-[1150px] mx-auto flex  justify-around flex-col md:flex-row px-10">
            <div className="flex flex-col space-y-5 md:mb-[100px] md:border-r-[1px] md:border-gray-200 md:pr-[100px] ">
              <div className="flex flex-col space-y-4 mb-[20px] ">
                <h4 className="text-2xl font-bold  font-Magenda mt-[50px]">
                  Tabitha Alms
                </h4>

                <Link href="/">
                  <a className="text-xs uppercase  font-Poppins underline underline-offset-1">
                    website
                  </a>
                </Link>
              </div>
              <div className="flex flex-col space-y-6 font-Poppins">
                <p className="font-Poppins text-[15px] ">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Mollitia
                </p>
                <Link href="/">
                  <a className="text-sm underline pb-2">Read More</a>
                </Link>
              </div>
              <div>
                <div
                  className="card__tabitha relative w-[358px] md:w-[480px] h-[318px] md:h-[420px] 
                   "
                >
                  <img
                    src="/Landing.png"
                    className="absolute bottom-10 md:bottom-20 w-[320px] md:w-[448px] h-[220px] md:h-[280px] left-5 md:left-4 object-cover"
                    alt=""
                  />
                </div>
              </div>
            </div>
            <div className=" md:px-10 flex flex-col space-y-5 md:pl-[40px] mb:[50px] ">
              <div>
                <div className="relative w-[358px] md:w-[480px] h-[318px] md:h-[420px] card__travel mt-[50px] ">
                  <img
                    src="/Travel.png"
                    className="absolute bottom-10 md:bottom-14 w-[320px] md:w-[448px] h-[220px] md:h-[320px] left-5 md:left-4 object-contain"
                    alt=""
                  />
                </div>
              </div>
              <div className="flex flex-col space-y-4 mb-[20px] ">
                <h4 className="text-2xl font-bold  font-Magenda">
                  Travel Adventures
                </h4>

                <Link href="/">
                  <a className="text-xs uppercase  font-Poppins underline underline-offset-1">
                    website
                  </a>
                </Link>
              </div>
              <div className="flex flex-col space-y-6 font-Poppins">
                <p className="font-Poppins text-[15px] ">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Mollitia
                </p>
                <Link href="/">
                  <a className="text-sm underline pb-2">Read More</a>
                </Link>
              </div>
            </div>
          </div>
          <div className="flex items-center justify-center mt-[50px] md:mt-0">
            <Link href="/work">
              <a className="px-5 py-2 border border-gray-400 rounded-full ">
                More Work
              </a>
            </Link>
          </div>
          <div>
            <h2 className="text-center font-Magenda text-3xl lg:text-6xl font-bold mt-[100px] mb-[50px] lg:mb-[100px]">
              Skills
            </h2>
            <div className="px-10 grid grid-cols-3 gap-2 lg:grid-cols-6 lg:gap-x-2 lg:gap-y-10 lg:px-20">
              {skills.map((skill) => (
                <Skills title={skill.title} image={skill.image} />
              ))}
            </div>
          </div>
          <div className="relative h-[180px] mt-[50px] md:mt-[100px] w-[1px] bg-black left-1/2 mb-[50px] lg:mb-[100px]" />
          <div className="text-center flex flex-col space-y-6 mb-[100px] md:mb-[200px] ">
            <h3 className="font-bold font-Magenda text-3xl">Say Hello</h3>
            <div className="md:mb-12">
              <p className="font-Poppins">Have a question?</p>
              <p className="font-Poppins">Want us to work together?</p>
            </div>
            <div className="flex items-center justify-center">
              <Link href="/contact">
                <a className="px-5 py-2 border border-gray-400 rounded-full ">
                  Contact Me
                </a>
              </Link>
            </div>
          </div>
          <div className="text-center font-Poppins text-[12px] mb-[50px]">
            <p className="text-gray-400">Copyright &copy; Brian Lusigi 2022</p>
          </div>
        </section>
      </main>
    </div>
  );
}
